#!/bin/bash
# TODO: Error Checks

# Credentials file checker ---> Start
oc_credentials check
VALID=$"(echo "$?")"

if [ $VALID = "1" ]; then
  tput setaf 1
  echo "One error with your credentias has occurred, Please run oc_cledentias to fix it!"
  tput sgr0
  exit 1
fi

CRED=~/.oC_credentials
  # shellcheck source=~/.oC_credentials
  . "$CRED"
# Credentials file checker <--- End

# Help ---> Start
display_help() {
    echo "Usage: $0 [user]" >&2
    echo
    echo "   -h, --help      This help output "
    echo
    echo "   [user]          displays only the output from the selected user"
    echo
    exit 1
}
    case "$1" in
      -h | -help | --help)
          display_help
          exit 0
          ;;
    esac
# Help <--- End


