#!/bin/bash
# TODO: Error Checks

# Credentials file checker ---> Start
oc_credentials check
VALID=$(echo "$?")

if [ $VALID = "1" ]; then
  tput setaf 1
  echo "One error with your credentials has occurred, Please run oc_credentials to fix it!"
  tput sgr0
  exit 1
fi

CRED=~/.oC_credentials
  # shellcheck source=~/.oC_credentials
  . "$CRED"
# Credentials file checker <--- End
cd "$oC_PATH"
sudo -u "$APACHE_USER"  php occ "$@"
