#!/bin/bash
printf "cache  --> "
find /mnt/owncloud/data -maxdepth 2 -wholename '*/data/*/cache' -print0 |xargs -r0 du --max-depth=0 -a| awk '{sum+=$1} END {print sum}'| numfmt --from-unit=1024 --to=iec
